Algoritmo "Cálculoarea"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/08/2022
Var
// Seção de Declarações das variáveis 
  b1, b2, h, area: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
       b1<-6
       b2<-8
       h<-5
       
       area<- (b1+b2)/2*h;
       escreval (area)

Fimalgoritmo